### ISSUE TITLE
Signout flow for Google OpenID

### ISSUE THREAD

**Issue by wizche** [damienbod/Blazor.BFF.OpenIDConnect.Template#33]
Installed the template, configured Google OpenID and login worked right away. Logout triggered the following error:
```
Failed to load resource: the server responded with a status of 500 ()
https:/…pi/Account/Logout:6Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Me/3+KaSpAYm2+KuY1SHLIpdPokHy9UlHUwUJeICJiY='), or a nonce ('nonce-...') is required to enable inline execution.
https:/…pi/Account/Logout:591Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-v8v3RKRPmN4odZ1CWM5gw80QKPCCWMcpNeOmimNL2AA=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-i5wdQEYWxSf0cisy2nmGBORIOnxxrxn/l1gIqCbATKA='), or a nonce ('nonce-...') is required to enable inline execution.
```

Testing under Linux with Chrome Version 109.0.5414.119 (Official Build) (64-bit)

**Comment by wizche** [comment]
Adding the sha256 to the CSP (in `SecurityHeadersDefinitions`) will fix the issue.
Now signin-out will trigger a `System.InvalidOperationException: Cannot redirect to the end session endpoint, the configuration may be missing or invalid.`. 
I suspect I need to configure the sign-out flow manually to trigger the token revocation @ Google... 
Do you have hints how to do it?

**Comment by damienbod** [comment]
Hi @wizche I am not sure if google supports signout. The AccountController sends a signout post request to google if configured. I will validate this.

Greetings Damien
