### ISSUE TITLE
index.html is missing and creating problems with 3rd Party Component Frameworks

### ISSUE THREAD

**Issue by dlandi** [damienbod/Blazor.BFF.OpenIDConnect.Template#37]
Hello, thank you so much for this template, but I have a problem.

You do not include an index.html in the Blazor Client "www.root" folder. 

Some 3rdParty Component frameworks require it, such as Blazor.Radzen. 

Please look at the "getting started" page here:
https://blazor.radzen.com/get-started

![image](https://user-images.githubusercontent.com/3196088/224836440-025e6d68-e270-49da-b5e0-1966e34385a5.png)

Because the index.html file is missing, some of the Radzen components won't render, such as the DropDown component here:
https://blazor.radzen.com/dropdown

I have tried manually adding the Index.html file to www.root, but that file doesn't appear to be loaded at runtime.

So, was there a reason to omit the index.html file from your template? 

And how can we add it back so that Blazor loads it correctly?

Thanks.

**Comment by dlandi** [comment]
Oh, I think I am supposed to be using "Pages\_Host.cshml" in this case. I'll get back to you with my results.

**Comment by dlandi** [comment]
Yep. That was it. My bad!

**Comment by damienbod** [comment]
cool, great you got it working

Greetings Damien
