### ISSUE TITLE
How to specify custom redirect_uri instead of https://localhost:5001/signin-oidc ??

### ISSUE THREAD

**Issue by eproadmin2** [damienbod/Blazor.BFF.OpenIDConnect.Template#38]
Hello,

Sorry but i am new to Blazor.

I am wondering how i could specify a custom redirect_uri instead of the default redirect_uri https://localhost:5001/**signin-oidc**

Thanks alot for your quick response.

**Comment by damienbod** [comment]
Hi @eproadmin2 
You can set this in the startup or in the configuration, a property exist for this, If you change this, it needs to match your server STS settings exactly.

´´´
options.CallbackPath = "/signin-oidc";
´´´

Greetings Damien

**Comment by eproadmin2** [comment]
Hello @damienbod,

Thanks for your quick reply and also for your amazing done job.

Do you have a link for #BuyMeACoffee ?

**Comment by damienbod** [comment]
No problem, you can add it like this:

´´´
...
options.Scope.Add("profile");
options.Events = new OpenIdConnectEvents
{
	OnRedirectToIdentityProvider = context =>
	{
		context.ProtocolMessage.SetParameter("acr_values", "urn:be:fedict:iam:fas:Level500");

		return Task.FromResult(0);
	}
};
´´´

**Comment by eproadmin2** [comment]
You are amazing. Really man.

Many thanks for your help.
