### ISSUE TITLE
Paramaters unused by identity server?

### ISSUE THREAD

**Issue by baonguyenbxl** [damienbod/Blazor.BFF.OpenIDConnect.Template#39]
Hello,

I would like to know if those parameters are essentials for the first GET request:
response_mode, code_challenge, code_challenge_method, x-client-SKU, x-client-ver

As the FAS give instructions below

![image](https://github.com/damienbod/Blazor.BFF.OpenIDConnect.Template/assets/69773267/b3d8e017-b0b8-49e4-8b19-f57b2bd28ff1)

Assuming that i will need to remove them, could you indicate how can I do that?

Many thanks for your help

**Comment by damienbod** [comment]
PKCE was added and is recommended now. You can set the UsePkce = false and it will not be sent. (code_challenge, code_challenge_method)

Refer to the OIDC core standards for the  for the response_mode . If the STS is OIDC, it must support you sending the response_mode 

The other 2 comes from the framework I think.

**Comment by baonguyenbxl** [comment]
Thanks alot.

Very nice.
