### ISSUE TITLE
Custom UseCallback?

### ISSUE THREAD

**Issue by billybeo** [damienbod/Blazor.BFF.OpenIDConnect.Template#40]
Hello,

I would like to use a custom callback, so I assign 'options.UseCallback = "/customCallback"', but I dont have a clue where and how to implement this callback?

I have seen that a default callback 'signin-oidc' is created in the template, but i don't find the handler.

Could you guide me please?

Thanks you

**Comment by damienbod** [comment]
You can do this in the OIDC challenge in the Server project program file
