### ISSUE TITLE
Callbackpath's handler

### ISSUE THREAD

**Issue by eproadmin2** [damienbod/Blazor.BFF.OpenIDConnect.Template#41]
Hello Damien,

Assuming that the callbackpath is assigned to "/oauthFAS/auth";

Do i need to create a new page in Client or a controller in Server? Or maybe change a parameter to bind the callback to an existing handler?

Thanks alot.

**Comment by eproadmin2** [comment]
It's keeps binding me to this error page:

![image](https://github.com/damienbod/Blazor.BFF.OpenIDConnect.Template/assets/123892712/b6b4d521-7cde-4acc-966e-8024c512d1e5)

![image](https://github.com/damienbod/Blazor.BFF.OpenIDConnect.Template/assets/123892712/54f3e5cd-2499-4e5d-a2e7-8f533d3d4952)

Help me please.

Thanks.

**Comment by damienbod** [comment]
Hi @eproadmin2 yes all OIDC challenge configurations are implemented in the server project program file. The client only communicates with the Server project.
