### ISSUE TITLE
Version 2.1.0 in nuget gallery is empty

### ISSUE THREAD

**Issue by TNT0305** [damienbod/Blazor.BFF.OpenIDConnect.Template#52]
at nuget.org, version 2.1.0 is about 24KB where the previous few versions are around 380KB

**Comment by damienbod** [comment]
Thanks for reportig, let me validate and fix

**Comment by damienbod** [comment]
Have you got .NET 8 installed?

What sdk version are you using?

```
dotnet --info
```

**Comment by damienbod** [comment]
Version 2.1.0 is broken

please use 2.0.4

dotnet new install Blazor.BFF.OpenIDConnect.Template::2.0.4 --force

I will fix this and update

**Comment by damienbod** [comment]
The publish build is broken...

**Comment by damienbod** [comment]
Updated a new version: 

´´´
dotnet new install Blazor.BFF.OpenIDConnect.Template::2.1.2
´´´

**Comment by TNT0305** [comment]
I only have up to 7.0.403 SDK.

But yes, the 2.1.2 appears to have the template included in the nuget.  Thanks a bunch!
