### ISSUE TITLE
Autoredirect to login

### ISSUE THREAD

**Issue by Schoof-T** [damienbod/Blazor.BFF.OpenIDConnect.Template#58]
Hi

I was wondering if it's possible to auto redirect to login page when the user is not logged in?
I used to do this with a component that redirected to the login page.

```
@inject NavigationManager Navigation

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateTo("api/Account/Login");
    }
}
```

But with the BFF pattern, the login page is an API method. And this method no longer works.
![image](https://github.com/damienbod/Blazor.BFF.OpenIDConnect.Template/assets/2319986/082aaa4b-91a1-4f24-88d6-1c839c464abb)

Thanks!

**Comment by Schoof-T** [comment]
After adding 

```
    services.AddAuthorization(authorizationOptions =>
    {
        authorizationOptions.FallbackPolicy = authorizationOptions.DefaultPolicy;
    });
```

In the Server project, I get automatically redirected to login on page load.

Is this the correct way to do this?

**Comment by damienbod** [comment]
Maybe like this?

```csharp
services.AddRazorPages().AddMvcOptions(options =>
{
    //var policy = new AuthorizationPolicyBuilder()
    //    .RequireAuthenticatedUser()
    //    .Build();
    //options.Filters.Add(new AuthorizeFilter(policy));
});

```

**Comment by Schoof-T** [comment]
That might also work (can't test it right now), but how does it know where to redirect to?

**Comment by damienbod** [comment]
There is a default path, or you can define this as you wish

**Comment by Schoof-T** [comment]
Yup, that works perfectly. Thank you :)
